/* Generated by tools/build_tw_fonts.py — do not edit. */
(function (root) {
  var EG = root.EnvGen || (root.EnvGen = {});
  EG.twFonts = {
    "kai": {
      "label": "全字庫正楷體（TW-Kai）",
      "common": "kai-common.woff2",
      "chunks": [
        {
          "file": "kai-00.woff2",
          "from": 592,
          "to": 6206
        },
        {
          "file": "kai-01.woff2",
          "from": 6207,
          "to": 14187
        },
        {
          "file": "kai-02.woff2",
          "from": 14188,
          "to": 18283
        },
        {
          "file": "kai-03.woff2",
          "from": 18284,
          "to": 23499
        },
        {
          "file": "kai-04.woff2",
          "from": 23501,
          "to": 29223
        },
        {
          "file": "kai-05.woff2",
          "from": 29225,
          "to": 34675
        },
        {
          "file": "kai-06.woff2",
          "from": 34677,
          "to": 39966
        },
        {
          "file": "kai-07.woff2",
          "from": 39967,
          "to": 65533
        },
        {
          "file": "kai-08.woff2",
          "from": 131072,
          "to": 135167
        },
        {
          "file": "kai-09.woff2",
          "from": 135168,
          "to": 139263
        },
        {
          "file": "kai-10.woff2",
          "from": 139264,
          "to": 143359
        },
        {
          "file": "kai-11.woff2",
          "from": 143360,
          "to": 147455
        },
        {
          "file": "kai-12.woff2",
          "from": 147456,
          "to": 151551
        },
        {
          "file": "kai-13.woff2",
          "from": 151552,
          "to": 155647
        },
        {
          "file": "kai-14.woff2",
          "from": 155648,
          "to": 159743
        },
        {
          "file": "kai-15.woff2",
          "from": 159744,
          "to": 163839
        },
        {
          "file": "kai-16.woff2",
          "from": 163840,
          "to": 167935
        },
        {
          "file": "kai-17.woff2",
          "from": 167936,
          "to": 172031
        },
        {
          "file": "kai-18.woff2",
          "from": 172032,
          "to": 176200
        },
        {
          "file": "kai-19.woff2",
          "from": 176201,
          "to": 195101
        }
      ]
    },
    "sung": {
      "label": "全字庫正宋體（TW-Sung）",
      "common": "sung-common.woff2",
      "chunks": [
        {
          "file": "sung-00.woff2",
          "from": 592,
          "to": 6206
        },
        {
          "file": "sung-01.woff2",
          "from": 6207,
          "to": 14187
        },
        {
          "file": "sung-02.woff2",
          "from": 14188,
          "to": 18283
        },
        {
          "file": "sung-03.woff2",
          "from": 18284,
          "to": 23499
        },
        {
          "file": "sung-04.woff2",
          "from": 23501,
          "to": 29223
        },
        {
          "file": "sung-05.woff2",
          "from": 29225,
          "to": 34675
        },
        {
          "file": "sung-06.woff2",
          "from": 34677,
          "to": 39966
        },
        {
          "file": "sung-07.woff2",
          "from": 39967,
          "to": 65533
        },
        {
          "file": "sung-08.woff2",
          "from": 131072,
          "to": 135167
        },
        {
          "file": "sung-09.woff2",
          "from": 135168,
          "to": 139263
        },
        {
          "file": "sung-10.woff2",
          "from": 139264,
          "to": 143359
        },
        {
          "file": "sung-11.woff2",
          "from": 143360,
          "to": 147455
        },
        {
          "file": "sung-12.woff2",
          "from": 147456,
          "to": 151551
        },
        {
          "file": "sung-13.woff2",
          "from": 151552,
          "to": 155647
        },
        {
          "file": "sung-14.woff2",
          "from": 155648,
          "to": 159743
        },
        {
          "file": "sung-15.woff2",
          "from": 159744,
          "to": 163839
        },
        {
          "file": "sung-16.woff2",
          "from": 163840,
          "to": 167935
        },
        {
          "file": "sung-17.woff2",
          "from": 167936,
          "to": 172031
        },
        {
          "file": "sung-18.woff2",
          "from": 172032,
          "to": 176200
        },
        {
          "file": "sung-19.woff2",
          "from": 176201,
          "to": 195101
        }
      ]
    }
  };
  if (typeof module === 'object' && module.exports) module.exports = EG.twFonts;
})(typeof globalThis !== 'undefined' ? globalThis : this);
