#!/usr/bin/env python3
"""Split the 全字庫 fonts (TW-Kai / TW-Sung, plus their Ext-B companions) into
small WOFF2 chunks that the app loads on demand.

Why: each font decodes to well over 30 MB of TrueType, past the limit of the
browser WOFF2 decoder, and an envelope only needs a few dozen characters.

Chunks per family:
  <fam>-common.woff2  Latin, punctuation, bopomofo, CJK symbols, full-width
                      forms + the 5,401 Big5 常用字. Always loaded.
  <fam>-NN.woff2      the remaining characters in contiguous code point ranges
                      (BMP from the main font, Plane 2 from the Ext-B font).

Usage:
  python3 tools/build_tw_fonts.py TW-Kai-98_1 TW-Kai-Ext-B-98_1 TW-Sung-98_1 TW-Sung-Ext-B-98_1
  (each argument is a .ttf or .woff2 path)
Requires: pip install fonttools brotli
"""
import json
import os
import sys

from fontTools import subset
from fontTools.ttLib import TTFont

CHUNK = 4096  # code points per range chunk (≈1.5 MB WOFF2 without hinting)
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'fonts', 'tw')
FAMILIES = [
    ('kai', '全字庫正楷體（TW-Kai）'),
    ('sung', '全字庫正宋體（TW-Sung）'),
]


def big5_level1():
    """Big5 常用字 (0xA440–0xC67E) as Unicode code points."""
    cps = set()
    for lead in range(0xA4, 0xC7):
        for trail in list(range(0x40, 0x7F)) + list(range(0xA1, 0xFF)):
            if (lead << 8) | trail > 0xC67E:
                continue
            try:
                cps.add(ord(bytes([lead, trail]).decode('big5')))
            except UnicodeDecodeError:
                pass
    return cps


# Non-ideographic blocks an envelope commonly uses; everything else goes into range chunks.
COMMON_BLOCKS = [
    (0x0020, 0x024F),  # Latin
    (0x02B0, 0x02FF),  # spacing modifiers
    (0x2000, 0x206F),  # general punctuation
    (0x20A0, 0x20CF),  # currency
    (0x2100, 0x21FF),  # letterlike, number forms, arrows
    (0x2460, 0x24FF),  # enclosed alphanumerics
    (0x2500, 0x25FF),  # box drawing, shapes
    (0x3000, 0x303F),  # CJK symbols and punctuation
    (0x3100, 0x312F),  # bopomofo
    (0x31A0, 0x31BF),  # bopomofo extended
    (0x3200, 0x33FF),  # enclosed CJK, CJK compatibility
    (0xFE10, 0xFE1F),  # vertical forms
    (0xFE30, 0xFE6F),  # CJK compatibility forms, small forms
    (0xFF00, 0xFFEF),  # half/full-width forms
]


def is_common(cp, big5):
    return cp in big5 or any(lo <= cp <= hi for lo, hi in COMMON_BLOCKS)


def to_ttf(src, tmp):
    font = TTFont(src)
    font.flavor = None
    font.save(tmp)  # decoding WOFF2 once is much faster than once per chunk
    return sorted(font.getBestCmap())


def write_subset(src, unicodes, path):
    opts = subset.Options()
    opts.flavor = 'woff2'
    opts.hinting = False
    opts.layout_features = []
    opts.name_IDs = [0, 1, 2, 3, 4, 5, 6, 13, 14]
    opts.notdef_outline = True
    font = TTFont(src)
    sub = subset.Subsetter(opts)
    sub.populate(unicodes=unicodes)
    sub.subset(font)
    font.flavor = 'woff2'
    font.save(path)
    print(f'  {os.path.basename(path)}: {len(unicodes)} glyphs {os.path.getsize(path) / 1e6:.2f} MB', flush=True)


def build(family, label, main_src, extb_src, common_set):
    tmp = os.path.join(OUT, f'.{family}-tmp.ttf')
    cps = to_ttf(main_src, tmp)
    common = [c for c in cps if is_common(c, common_set)]
    common_file = f'{family}-common.woff2'
    write_subset(tmp, common, os.path.join(OUT, common_file))
    in_common = set(common)
    sources = [(tmp, [c for c in cps if c not in in_common])]
    tmp2 = os.path.join(OUT, f'.{family}-extb-tmp.ttf')
    sources.append((tmp2, [c for c in to_ttf(extb_src, tmp2) if c >= 0x20000]))
    chunks = []
    for src, rest in sources:
        for i in range(0, len(rest), CHUNK):
            part = rest[i:i + CHUNK]
            name = f'{family}-{len(chunks):02d}.woff2'
            write_subset(src, part, os.path.join(OUT, name))
            chunks.append({'file': name, 'from': part[0], 'to': part[-1]})
        os.remove(src)
    return {'label': label, 'common': common_file, 'chunks': chunks}


def main():
    if len(sys.argv) != 5:
        sys.exit(__doc__)
    os.makedirs(OUT, exist_ok=True)
    common_set = big5_level1()
    manifest = {}
    for idx, (family, label) in enumerate(FAMILIES):
        print(family, flush=True)
        manifest[family] = build(family, label, sys.argv[1 + 2 * idx], sys.argv[2 + 2 * idx], common_set)
    js = os.path.join(OUT, 'manifest.js')
    with open(js, 'w', encoding='utf-8') as f:
        f.write('/* Generated by tools/build_tw_fonts.py — do not edit. */\n')
        f.write('(function (root) {\n  var EG = root.EnvGen || (root.EnvGen = {});\n')
        body = json.dumps(manifest, ensure_ascii=False, indent=2).replace('\n', '\n  ')
        f.write('  EG.twFonts = ' + body + ';\n')
        f.write("  if (typeof module === 'object' && module.exports) module.exports = EG.twFonts;\n")
        f.write("})(typeof globalThis !== 'undefined' ? globalThis : this);\n")
    print('wrote', js)


if __name__ == '__main__':
    main()
